### ISSUE TITLE
UPE U rotated by 180 degrees 2012 -- 2015

### ISSUE THREAD

**Issue by mankoff** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#1]
![image](https://user-images.githubusercontent.com/145117/92995442-99d11e00-f4b8-11ea-9498-7fc6b05e5efa.png)

**Comment by mankoff** [comment]
Note - it appears there is a different shift from 2012-2013, and then 2013-2015.

**Comment by mankoff** [comment]
This issue can be solved with the following algorithm. Further input is needed from PROMICE to fill in the precise details.

```
Determine precise dates of AWS maintenance in 2012, 2013 and 2015.
Subtract X0 degrees from the data between 2012 and 2013.
Subtract X1 degrees from the data between 2013 and 2015.
```

Notes:

- X0 and X1 can be determined by looking at the AWS Maintenance Sheets
- As with all wind direction data, even when not rotated by ~180 degrees: The station rotates over the course of the season. It is up to the end user to try to account for this, include it in an error analysis, fit a linear trend between the start and stop directions, etc.

**Comment by BaptisteVandecrux** [comment]
![image](https://user-images.githubusercontent.com/35140661/217282036-e6e67f8d-ba8d-4279-a13a-4ca7b1b010f8.png)

wdir_u rotated by 180deg between 2012-08-11 and 2015-08-03 in the next release

**Comment by BaptisteVandecrux** [comment]
Now released on the dataverse: https://doi.org/10.22008/FK2/IW73UU
