### ISSUE TITLE
EGP: Failing SR50s in winter 2016 and spring 2019?

### ISSUE THREAD

**Issue by BaptisteVandecrux** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#10]
First of all, the PROMICE website shows HeightSensorBoom and HeightStakes, not snow and surface height as the axis labels suggest.

Second, why is there a plateau Dec. 2016 Jul. 2017 and Apr-Jul 2019? 
The other sensors are working fine but hard to think that there is simply no snowfall during these periods.

![image](https://user-images.githubusercontent.com/35140661/97144608-0e100a00-1765-11eb-8026-4c07b2da142c.png)
![image](https://user-images.githubusercontent.com/35140661/97144655-1ff1ad00-1765-11eb-9272-5f760a85685b.png)

**Comment by robertfausto** [comment]
It seems the station is operating normally, but it is hard tell without a comparison to e.g. the nearby GC-Net station or a RCM. See plot after temperature correction:
![EGP_SR50](https://user-images.githubusercontent.com/71429231/97300135-50fdda80-1856-11eb-8bc0-3f2decb0a934.png)

**Comment by BaptisteVandecrux** [comment]
Comparison with the FirnCover station: looks like the surface height kept increasing over the winter 2017 although the station stopped recording. PROMICE station shows stable surface height for the same period.

![image](https://user-images.githubusercontent.com/35140661/97309796-c7083e80-1862-11eb-873b-c76f879e3225.png)

**Comment by robertfausto** [comment]
It seems to me that the two records are quite similar. What happened to the firncover record? I mean the data gap around 2017-01? Yes, it seems that the firncover station is gaining around 10 cm of snow (period around 2017-01), but without knowing what happened during the firncover data gap, the problem could also be with that data record. It could be that EGP is slowly starting to tilt with the SR50 toward the surface offsetting minor snowfall?

**Comment by BaptisteVandecrux** [comment]
Pictures from before (left) and after (right) 2017 maintenance. Everything looks fine.
I guess we can attribute the (minor) discrepancy FirnCover, PROMICE AWS and PROMICE stake assembly to potential tilts and to heterogeneous snow accumulation due to wind redistribution.

Conclusion: it doesn't snow (much) during winter 2017 and 2019.

![image](https://user-images.githubusercontent.com/35140661/97410085-e5237c80-18fe-11eb-9db4-462ca37fe6eb.png)
