### ISSUE TITLE
ZAK_Uv3 summer albedo gets down to 0.2

### ISSUE THREAD

**Issue by BaptisteVandecrux** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#125]
![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/5d527c1d-1098-49f1-b59f-7cb6739c2a9b)

@signehl is that expected?

**Comment by signehl** [comment]
Albedo of 0.2 is not uncommon for the data series and it has also been observed from space: Google Earth Engine Albedo Inspector (https://fsn1995.users.earthengine.app/view/albedoinspector).
![ee-chart_albedo_vlaues_zac_u](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/71708740/c3ff1167-9844-4985-a6eb-52b0380a0e20)

**Comment by BaptisteVandecrux** [comment]
Great! No problem then!
