### ISSUE TITLE
a month-plus of empty data at the start of the SWC_O record

### ISSUE THREAD

**Issue by jasonebox** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#127]
in the SWC_O data I get from thredds, I find more than a month of NaNs from a time before the AWS was installed.

I guess the logger was on/logging in shipment.

The bad data are from
2022-06-29 10:00:00
to
2022-08-02 16:00:00

...the first complete hour is 2022-08-02 17:00:00 and even that hour may have issues. Safe may be to start with 17 UTC on 2 aug, 2022

**Comment by PennyHow** [comment]
Good spot! Should be resolved with this merge request over on our aws-l0 repo: https://geusgitlab.geus.dk/glaciology-and-climate/promice/aws-l0/-/merge_requests/53

**Comment by BaptisteVandecrux** [comment]
fixed in dataverse release V13
![billede](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/1261917f-2a8d-47f1-81ef-ebd40f342a70)
