### ISSUE TITLE
KPC_L outgoing longwave radiation shift in July 2019

### ISSUE THREAD

**Issue by mvantiggelen** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#130]
It appears that there is a systematic decrease of ~10Wm-2 in outgoing longwave radiation (ulr) at KPC_L from 12 July 2019 onwards. Values after this date are not consistent with a melting surface.
At KPC_U there is also a shift, although the new values are consistent with a melting surface and window heating of the CNR sensor.

Data from dataverse version 12.

![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/39654529/4e65be4f-ec17-4696-962d-48ea7698b4f2)

**Comment by BaptisteVandecrux** [comment]
After a lot of digging we identified a swap of the calibration constants of the radiometers at KPC_U and KPC_L.

Should be fixed  in dataverse release V20 https://doi.org/10.22008/FK2/IW73UU and on thedds
