### ISSUE TITLE
Flagging bad pressure data at GC-Net stations

### ISSUE THREAD

**Issue by ladsmund** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#140]
## Note

The stations : NAE, CEN2, HUM, NAU, NEM, NSE, SDM, TUN are having issue with their pressure data beginning in December 2023.

## What is the issues?
DMI has reported issue in the pressure data from our BUFR files.
I noticed periodes with erroneous data and missing data in both our L0 datasets and L3 data products.
The following figures shows the pressure data fro the stations in the period from 2023-11-01 to 2024-02-16.

![SDM](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/1437005/7d706561-d3cb-419d-b62d-39b9d0d1a9bb)
![NSE](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/1437005/64490ba3-eb47-4bd5-8b1e-f70e658a6798)
![NEM](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/1437005/95adac47-80be-4776-b4b8-01cbe0567b4e)
![NAU](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/1437005/94593134-342b-4d3e-b9ec-3c4f44c27b0c)
![HUM](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/1437005/32d4c22f-73c3-4fc3-980b-9495483e6523)
![CEN2](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/1437005/b13ce33c-13c6-447b-89ae-8caa9286595c)
![NAE](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/1437005/7124e8c2-c5f1-4ae5-aacd-f7eb7b4a09e7)
![TUN](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/1437005/e8e6e444-730d-4180-b13b-574752c1ef41)

**Comment by ladsmund** [comment]
The error seems to be related to the low temperature issues with our luft sensor.
It is also the case in April 2023 for TUN
<img width="2052" alt="image" src="https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/1437005/53bbd030-15ab-4775-8573-dd4c2912e4c5">

**Comment by ladsmund** [comment]
There is something suspicious happening with the CEN2 L3 data in addition to the pressure data.
It looks like there is a lower temperature threshold on -35C from midt December. The measurements are available as L0.

<img width="1447" alt="image" src="https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/1437005/fac932a0-1f0b-41b0-9f44-eb63e8633c5d">

**Comment by ladsmund** [comment]
I looks like there is a lower pressure threshold at 709hPa.
<img width="1447" alt="image" src="https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/1437005/c2c494a4-f389-4135-9a19-6e318fc61a5b">

**Comment by ladsmund** [comment]
> I looks like there is a lower pressure threshold at 709hPa.
> <img alt="image" width="1447" src="https://private-user-images.githubusercontent.com/1437005/305923650-c2c494a4-f389-4135-9a19-6e318fc61a5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNDAyNzgsIm5iZiI6MTcwODMzOTk3OCwicGF0aCI6Ii8xNDM3MDA1LzMwNTkyMzY1MC1jMmM0OTRhNC1mMzg5LTQxMzUtOWExOS02ZTMxOGZjNjFhNWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTlUMTA1MjU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGVlMTgxMGFkZmQyZGMzN2QwZGU2MTAxMjk2ZDQ5YzU3M2FkY2YzZjFmMmUwZDNhYWM3OTU0NzZmYjhhY2NiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sfQ4NzzpQliTtR8Xk-sv8Eo2-Iynvp7zNFmX-vS0DmU">

It is because of the percentile qc

**Comment by PennyHow** [comment]
If this is related to the lufft sensor, similar to the issue with temperature, then we should make an adjustment in pypromice `L0toL1` (like in [this PR](https://github.com/GEUS-Glaciology-and-Climate/pypromice/pull/214#issue-2016702645)) and/or alter the [variable thresholds](https://github.com/GEUS-Glaciology-and-Climate/pypromice/blob/main/src/pypromice/process/variables.csv). Good catch!

**Comment by BaptisteVandecrux** [comment]
Hi Mads,
I usually leave the issue open until the problem is also fixed on the dataverse, where most users get the data.
@PennyHow is the monthly upload to dataverse reactivated?

**Comment by PennyHow** [comment]
It's not been reactivated yet, but I can just manually trigger it whenever it is needed. Next release is scheduled for beginning of March, but we can make exceptions if there are any urgent data updates.

**Comment by BaptisteVandecrux** [comment]
I am flagging additional pressure outliers at HUM for 2022-23:
![billede](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/d88f6b0a-81d5-4894-9c8f-b7958661e2ec)

**Comment by BaptisteVandecrux** [comment]
new flags on p_u p_l at NEM
![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/1bec9f3c-2fc7-48bc-8420-63e4db7225f2)
![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/67f94394-84bc-491d-8b48-7c2642c86e2e)

No idea why p_i was not available


and NSE
![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/063003de-c6d3-4a11-a75b-01f783fc07a5)

**Comment by BaptisteVandecrux** [comment]
Filtered out and released in https://dataverse.geus.dk/dataset.xhtml?persistentId=doi:10.22008/FK2/IW73UU
