### ISSUE TITLE
Problem with MIT position in 2021

### ISSUE THREAD

**Issue by sjnoone** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#149]
## Note

The *MIT_hour*, *2021*, 
![MIT_hour_cleaned_plots](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/28791613/29260ea7-7522-4137-84e1-ba6562454578)

## there is a major shift in longitude in 2021 and looks like an error rather than a legitimate shift
See attached plots showing the shift .

**Comment by BaptisteVandecrux** [comment]
Hi Simon,
I implemented new filters on the MIT positions:
![billede](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/fc383482-8cf6-4d6b-896b-bc35dc600204)

I let you know when the updated files are available

**Comment by BaptisteVandecrux** [comment]
@sjnoone please be aware that MIT is located on a local glacier (maybe mixed pixel in your case).
Also the data filtering is still under way and not at the same stage as the ice sheet weather stations (see e.g. #54)

**Comment by BaptisteVandecrux** [comment]
Largest outlier removed and data release in V17 on the dataverse.
Remaining visible outliers should be easily removed by a rolling median or loess filter.

![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/8b5af890-2d2c-4ec0-82b4-b7e18b36f85e)
