### ISSUE TITLE
Station rotated about 50 degrees

### ISSUE THREAD

**Issue by mankoff** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#15]
```python
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("Roof_GEUS_hour.csv", parse_dates=True, index_col=0)
df = df['2022-11-09':'2022-11-11']
df[['z_boom_u','z_boom_u']].plot()
df[['wdir_l','rot']].plot()
```

The above code produces the following graphic
![Screenshot_2022-11-20_082838](https://user-images.githubusercontent.com/145117/202913707-f07e274e-d62f-4357-b04e-7f6811360bb8.png)

It appears the station was rotated by ~50ish degrees for ~12 hours on ~10 November.

This affects many sensors I think. Not just wind, but tilt, maybe radiation if the par was far from south, etc.

The lower wind direction appeared stuck at the same time, so no correction needed there (see #13), but the upper wind direction, not plotted, can be corrected for this rotation.

**Comment by BaptisteVandecrux** [comment]
Closing this one as a test-case for flagging and adjustment.
The implications of station rotation on wind direction can be corrected through the adjustment CSV, or flagged if the anemometer was immobilized during the same period (case here).

There are still ongoing discussions about how to include station rotation in the tilt correction of shortwave radiation data: https://github.com/GEUS-Glaciology-and-Climate/pypromice/issues/28
