### ISSUE TITLE
NUK_U problem with altitude in 2007

### ISSUE THREAD

**Issue by sjnoone** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#150]
## Note

The *NUK_U_hour*, *2007*, Most of 2007 has an altitude value of 1 entered for this station.

see plots.
![NUK_U_hour_cleaned_plots](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/28791613/07e53b00-dfd0-4923-ad38-18c96766281a)

**Comment by BaptisteVandecrux** [comment]
I have applied some new filters:
![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/742223e9-9a8b-4cc4-b831-3d8925268eba)

This will be fixed in the next release on the dataverse.

**Comment by sjnoone** [comment]
I only looked at the hourly files initially but all the issues I have highlighted are found across all timescales -daily and monthly as well.
Simon

**Comment by BaptisteVandecrux** [comment]
Largest outlier removed and data release in V17 on the dataverse.
Remaining visible outliers should be easily removed by a rolling median or loess filter.

![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/5724b0f8-55ed-402f-bcbb-76efa744aae9)
