### ISSUE TITLE
Stations with no GPS observations

### ISSUE THREAD

**Issue by sjnoone** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#152]
Hi,
I have noticed that many of the stations in this dataset have rows with observations but no GPS location information. Can you pls advise on how best to deal with this issue please?
e.g see CEN1 2017-2019

Simon

**Comment by BaptisteVandecrux** [comment]
Hi Simon,
Indeed, for some periods and stations, the GPS was either failing or not installed.
We currently do not provide a "best guess" for positions during those periods or at those stations.
Doing so would require providing an origin flag for each value.
In the meantime we encourage user to either 1) do their own interpolation of position if they find it suitable; or 2) select the only the periods where postions are measured.
We'll discuss it with our team and decide on the best approach.

**Comment by sjnoone** [comment]
OK thanks, pls let me know . It would be a shame not use all those observations.

Simon

**Comment by BaptisteVandecrux** [comment]
Closing here because it is not a data-related issue. 
Interpolation would need an update of the processing scripts.
I opened this feature request on our processing code repo: https://github.com/GEUS-Glaciology-and-Climate/pypromice/issues/236
