### ISSUE TITLE
location altitude query KPC_U

### ISSUE THREAD

**Issue by sjnoone** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#153]
## Note

The KPC_U_, 2019, shows a big shift in altitud around 2019 nearly 300 metres with no obvious large shifts in lat or lon so is this a genuine station move or an error in GPs transmission?
![KPC_U_hour_cleaned_plots](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/28791613/de235b72-68e7-4b0c-9ce1-14eb3ceba9f5)

**Comment by BaptisteVandecrux** [comment]
Now filtered:
![billede](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/11c204c9-589e-4cd8-857e-8ecaeb9af547)

**Comment by sjnoone** [comment]
Hi Baptiste, Thanks for fiixng these issues. Can you let me know where I can find the updated dataset?

**Comment by BaptisteVandecrux** [comment]
Hi Simon,
There is a release on its way on the dataverse. But in the meantime you can find the updated files on https://thredds.geus.dk/thredds/catalog/catalog.html
I'll close the issues when the dataverse is also updated.
Let me know if you see anything else.
Thanks for your help cleaning the data!

**Comment by BaptisteVandecrux** [comment]
Largest outlier removed and data release in V17 on the dataverse:
![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/afa282eb-edf7-4949-8831-dd47185cacc1)

Remaining visible outliers should be easily removed by a rolling median or loess filter
