### ISSUE TITLE
problem with GPS coordinates at NUK_L

### ISSUE THREAD

**Issue by sjnoone** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#154]
## Note

The NUK_L,  in 2008/09 has some large shifts in altitude over 300m and some shifts in lat/longs in 2011 and 2014 are these correct?
![NUK_L_hour_cleaned_plots](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/28791613/70e12035-6c1f-47f9-8651-9410049f339d)

**Comment by BaptisteVandecrux** [comment]
Now filtered:
![billede](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/56ca31a4-829c-4d54-81b5-91963ad24406)

**Comment by BaptisteVandecrux** [comment]
Largest outlier removed and data release in V18 on the dataverse:
Remaining visible outliers should be easily removed by a rolling median or loess filter
Flat periods should be removed with persistence QC

![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/93e9b897-089b-4e18-b1a5-f6b9f18baadc)
