### ISSUE TITLE
QAS_U large shift in altitude 

### ISSUE THREAD

**Issue by sjnoone** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#155]
## Note

The QAS_U , *2010-2012 shwos large shifts in altitude are these correct as no appara
![QAS_U_hour_cleaned_plots](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/28791613/fae8af21-38ef-4128-be1c-9622655ae568)
nt alrge hsift in lat/lon?

**Comment by BaptisteVandecrux** [comment]
now filtered:
![billede](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/8e0e4217-ea94-4e65-9cad-3fd8e5ff5651)

I also suggest you try rolling median or loess filter instead of running mean. This may give a smoother output.

**Comment by BaptisteVandecrux** [comment]
Largest outlier removed and data release in V18 on the dataverse:
Remaining visible outliers should be easily removed by a rolling median or loess filter
Flat periods should be removed with persistence QC

![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/c899cc18-5b67-4ce1-8416-22c290ba53ef)
