### ISSUE TITLE
UWN location query

### ISSUE THREAD

**Issue by sjnoone** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#156]
## Note

The UWN in 2021 shows some unusual large shifts in location, also it appears to be location in Norway is this correct .
![UWN_hour_cleaned_plots](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/28791613/408c9fa9-4bbd-4706-b912-e81bf0a5f74c)

**Comment by BaptisteVandecrux** [comment]
Hi Simon,

Yes UWN is in Norway. It is maintained by another institute and GEUS only distribute the data.
We are not responsible for the data quality of this station so I would leave it aside for now.

It is also the case of several of the stations: NUK_K, MIT, WEG, ZAK that are on small Greenlandic glaciers. 

The station with highest quality can be selected from [AWS_metadata.csv](https://dataverse.geus.dk/file.xhtml?persistentId=doi:10.22008/FK2/IW73UU/0RH4WD&version=16.0) the sites that have location_type ==  ice sheet.
