### ISSUE TITLE
location altitude query KAN_M

### ISSUE THREAD

**Issue by sjnoone** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#157]
Kan_M 2009-2010 show some altitude outliers throughout this period and no big shifts in location so these altitude values may be errors.

**Comment by BaptisteVandecrux** [comment]
also flagged:
![billede](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/1aec55bf-ff6c-4aa7-9ed1-adcfb538f8b2)

**Comment by BaptisteVandecrux** [comment]
Largest outlier removed and data release in V17 on the dataverse:
Remaining visible outliers should be easily removed by a rolling median or loess filter
Flat periods should be removed with persistence QC

![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/1e384491-494c-4bda-846f-0cfa0084097d)
