### ISSUE TITLE
location altitude query TAS_L

### ISSUE THREAD

**Issue by sjnoone** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#158]
TAS_L 2007 first few entries have 0 as altitude and then several other suspect altitude values

**Comment by BaptisteVandecrux** [comment]
also filtered now:
![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/09ff6125-c250-45cf-9c18-9b4ee3f14083)

**Comment by BaptisteVandecrux** [comment]
Largest outlier removed and data release in V18 on the dataverse:
Remaining visible outliers should be easily removed by a rolling median or loess filter
Flat periods should be removed with persistence QC

![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/b325ef93-c02b-4ed7-965e-2e27ca382d6e)
