### ISSUE TITLE
location altitude issue TAS_U

### ISSUE THREAD

**Issue by sjnoone** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#159]
TAS_U 2009 some suspect altitude values of 57 when most altitude for this station are in 570-580 range

**Comment by BaptisteVandecrux** [comment]
![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/8b614554-617e-4e29-b708-5c09cd6d705c)
now filtered

**Comment by BaptisteVandecrux** [comment]
Largest outlier removed and data release in V18 on the dataverse:
Remaining visible outliers should be easily removed by a rolling median or loess filter
Flat periods should be removed with persistence QC

![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/6f09bed6-8671-4f2d-94df-f0865d275623)
