### ISSUE TITLE
CEN1 file missing 2017 and 2018 in the Edition 3 AWS dataset

### ISSUE THREAD

**Issue by BaptisteVandecrux** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#16]
In the file  "CEN_hour_v03.txt" in AWS one boom tripod Edition 3, https://doi.org/10.22008/FK2/8SS7EW/7B3WOD, GEUS Dataverse, V2 starts in 2017

while "CEN1_hour_v04.csv" in AWS one boom tripod Edition 4, https://doi.org/10.22008/FK2/IW73UU/Y8BVBN, GEUS Dataverse, V1,  starts in September 2019.

**Comment by PennyHow** [comment]
`L0 raw` 2017-2018 data for `CEN1` is included in `CEN1_2019_raw.txt` for Edition 4. 

Given that Edition 3 is an archive dataset, we are not going to modify it and instead preserve it in its original state. Therefore, no action is needed.

**Comment by BaptisteVandecrux** [comment]
Thanks for the info!
I'm a bit confused with the naming of different stations at this site:
- In the `L0/raw` folder there is no "CEN" station at this site. Only "CEN1" and "CEN2". 
- The `L0/raw/CEN1.toml` file has `station_id = 'CEN'`
- The `L0/raw/CEN1.toml` file has `station_id = 'CEN1'`
- The  aws-l3/level_3 has 'CEN', 'CEN1', and 'CEN2' folders

Are CEN and CEN1 different stations? Are they being merged into 'CEN'?
But then the transmission and the raw logger files are not processed under the same station ID.

**Comment by PennyHow** [comment]
`CEN` changed to `CEN1` but it looks like we didn't update the `station_id` in the `raw/CEN1.toml` file like you pointed out. This is creating its file name as `CEN` instead of `CEN1` in the `L3` products. 

Thanks for flagging this. This is an easy fix.

**Comment by PennyHow** [comment]
This has been cleaned up in the `aws-l0` and `aws-l3` repos now, so data from this station is labelled as `CEN1` only. 

@patrickjwright has also updated this in `pypromice` [here](https://github.com/GEUS-Glaciology-and-Climate/pypromice/pull/83), with WMO submissions made from `CEN2` renamed to `CEN`. This was requested to remain consistent with WMO station identifiers.
