### ISSUE TITLE
location altitude issue datatraverse SCO_U

### ISSUE THREAD

**Issue by sjnoone** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#161]
Found an issue with SCO_U altitude values in 2010/11. Altuitude jumps down from 960's to 440's for this period.

**Comment by BaptisteVandecrux** [comment]
Hi Simon,
This should have been solved in the dataverse V19 published this morning:
![SCO_U_0](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/4fa38c53-b6f3-42f5-af31-96df71ed327a)
