### ISSUE TITLE
location altitude issue datatraverse THU_U

### ISSUE THREAD

**Issue by sjnoone** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#162]
THU_U has some altitude values in 2017/2017 and mostly 2022 that look to be errors , more than 200-300m below the average altitude values

**Comment by BaptisteVandecrux** [comment]
This should have been solved in the dataverse V19 published this morning:
![THU_U_0](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/df2ea009-20f4-4338-a0e3-9d0db12d6750)

Note that a 2-week rolling window median filter (in green) is still fluctuating quite a bit. We are looking into efficient way of smoothing and inter/extrapolating the coordinates.
