### ISSUE TITLE
HUM - erroneous wdir data from lower boom  

### ISSUE THREAD

**Issue by ladsmund** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#165]
There is an issue with the `wdir_l` measurements since February 15th.

The figure below shows a shift in the `wdir_l` values from February 15th. The difference plot also shows a slightly increase in variance from that date. The offset and difference variance continues after the station visit in May.

I think there is a problem with the rotary encoder in the anemometer and we should therefore discard the data until the anemometer is changed.

The instantaneous values are taken from the lower boom anemometer until the last visit where the logger program is updated to use the upper boom. 

I suggest we discard the wind direction data:
* wdir_l from 2024-02-26T07:00 UTC
* wdit_i from 2024-02-26T07:00 UTC to 2024-05-21T20:00 UTC

![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/1437005/719f7e73-a5e8-43db-944a-5ced12663031)

**Comment by BaptisteVandecrux** [comment]
![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/477ad76b-c7f6-4b74-b3a3-b9e8a408bb83)
should be fixed at the next processing

**Comment by BaptisteVandecrux** [comment]
Fixed in dataverse release V20 https://doi.org/10.22008/FK2/IW73UU
