### ISSUE TITLE
QAS_L v2 

### ISSUE THREAD

**Issue by ladsmund** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#168]
The station was fallen over between the 2023 and the 2024 visits.

Station condition on arrival 2024-09-01:
![image](https://github.com/user-attachments/assets/e527ad65-71bb-4eb7-b7f8-468f72a5d5ec)

Raw tilt l0 measurements from raw 10min data files:
![image](https://github.com/user-attachments/assets/0358ba62-08dc-48cf-a1d7-e698c32cc09b)
<img width="840" alt="image" src="https://github.com/user-attachments/assets/2f51a979-a1ba-401e-a81f-36f22b9e56e9">

It looks like the tripod changed posture around 2024-01-29. 

The QAS_L wind variables started to diverge significantly from QAS_Lv3 around 2024-06-09
<img width="1617" alt="image" src="https://github.com/user-attachments/assets/fc3f3e6d-f452-445e-8ce4-55e0eb9a0e62">

I therefore suggest we flag all sensors that depends station posture either from 2024-01-29 or from start June.

* wind speed and direction
* solar radiation
* thermistor string ?
* z-boom height

**Comment by ladsmund** [comment]
It looks like the collapse was triggered by melting.
<img width="1047" alt="image" src="https://github.com/user-attachments/assets/a7c52852-c17f-43e1-a527-ccb23aa6c744">

**Comment by BaptisteVandecrux** [comment]
Flagging in https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/commit/d31d2bf320463b8e934818865762f38c66d5ca65  from 2024-06-04 based on shortwave radiation.
We need to reassess after we get the 2024 logger files in (atm, winter data are only daily transmission).

**Comment by BaptisteVandecrux** [comment]
Bad data removed in dataverse release V20 https://doi.org/10.22008/FK2/IW73UU
