### ISSUE TITLE
thredds access and z_surf_combined

### ISSUE THREAD

**Issue by jasonebox** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#169]
working with z_surf_combined that incidentally is not in all file so I don't get something. Anyway, I get

```OSError: [Errno -90] NetCDF: file not found: b'https://thredds.geus.dk/thredds/dodsC/aws/l3sites/netcdf/month/SDM_month.nc'```

The following uncommented URL was working, but not today. The commented URLs didn't work and/or didn't have the z_surf_combined

```
    url=f'https://thredds.geus.dk/thredds/dodsC/aws/l3sites/netcdf/{timeframe}/{site}_{timeframe}.nc'
    # url=f'https://thredds.geus.dk/thredds/dodsC/aws_l3_station_netcdf/level_3/{site}/{site}_{timeframe}_month.nc'
    # url=f'https://thredds.geus.dk/thredds/dodsC/aws_l3_time_netcdf/level_3/{timeframe}/{site}_{timeframe}.nc' # no z_surf_combined
    
    ds_lazy=xr.open_dataset(url) 
    list(ds_lazy.keys())
```

**Comment by BaptisteVandecrux** [comment]
Hi Jason,
Indeed some files were missing from the thredds `month` folder. Should be fixed now!
Thanks!
