### ISSUE TITLE
NAE data intermittent

### ISSUE THREAD

**Issue by BaptisteVandecrux** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#18]
Entire station giving intermittent data:

![image](https://user-images.githubusercontent.com/35140661/203754265-b84cf935-cbe7-49d2-aa43-63756afbb716.png)

![image](https://user-images.githubusercontent.com/35140661/203754971-90c3adab-128f-4396-8390-69a2c8428245.png)

**Comment by PennyHow** [comment]
`NAE` `L3` data product purely from `L0 tx` for now, which indeed does look patchy. In addition, it looks like the transmissions stopped on `2022-09-07 19:00:00`. We are not sure why, but hopefully there will be some clarification about what happened when the station is revisted and `L0 raw` data is downloaded.

**Comment by BaptisteVandecrux** [comment]
Back to normal after 2023 field visit
