### ISSUE TITLE
SR50 Sonic Ranger: stake height / snow depth are swapped on UPE_L

### ISSUE THREAD

**Issue by mankoff** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#2]
The UPE_L SR50s are swapped. The AWS is reported as on the stakes and the stakes reported as on the AWS.

![image](https://user-images.githubusercontent.com/145117/92995483-f6ccd400-f4b8-11ea-9006-209d69b0f21d.png)

**Comment by mankoff** [comment]
This solution needs specific AWS maintenance dates from a PROMICE scientist.

Between the problematic dates, users should use the correct SR50, ignoring the incorrect labeling.

**Comment by robertfausto** [comment]
The SR50 labels for the UPE_L data product is now correctly assigned for the periods in question.
