### ISSUE TITLE
CP1, bad instantaneous pressure

### ISSUE THREAD

**Issue by patrickjwright** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#20]
Starting 2023-01-03, CP1 `p_i` is bad:

![image](https://user-images.githubusercontent.com/10144675/210798021-0ae8eb5e-ed64-4d65-ab72-af4db3b7e32c.png)

![image](https://user-images.githubusercontent.com/10144675/210798075-2e43fd01-6706-493a-a019-b7e8802391fd.png)

**Comment by BaptisteVandecrux** [comment]
p_u and p_i flagged and removed during two short periods
![image](https://user-images.githubusercontent.com/35140661/217497285-0318951a-cb08-4590-8a99-fc1210e8ba0c.png)

Note that p_u started failing 1.5 days before p_i

The station can be reactivated in the bufr distribution work.
