### ISSUE TITLE
NAU, bad instantaneous pressure

### ISSUE THREAD

**Issue by patrickjwright** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#21]
Starting 2022-12-23, NAU `p_i` is bad.
![image](https://user-images.githubusercontent.com/10144675/210799102-8a6bd49f-dd1e-4c1f-b232-8911e684a474.png)
![image](https://user-images.githubusercontent.com/10144675/210799161-f282655d-2cc9-4d33-abe1-fb089a5ba498.png)

**Comment by BaptisteVandecrux** [comment]
bad p_i and p_u flagged (and removed) in the next release:
![image](https://user-images.githubusercontent.com/35140661/217493143-16c6fd54-494b-496d-9199-34cd3773a22f.png)

the last flag is open-ended so new data will remain flagged as bad until good data is seen again and an end date can be added to the `flags/NAU.csv` file
