### ISSUE TITLE
KAN_U level 3 data file missing data before 2013

### ISSUE THREAD

**Issue by BaptisteVandecrux** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#23]
Station was installed in 2009

![image](https://user-images.githubusercontent.com/35140661/211280347-8002f5cd-cba9-427a-8b45-9ebb7fbb6aa9.png)

**Comment by PennyHow** [comment]
Confirmed. `L0 raw` files only start from `KAN_U_2014_raw.txt` even though we have data from 2009 in our archive space. Perhaps @robertfausto can clarify this?

**Comment by BaptisteVandecrux** [comment]
Identified the L0 files to be used with @robertfausto . Working on it at the moment.

**Comment by BaptisteVandecrux** [comment]
Two issues remaining:
 - I cannot find file "KAN_U_2013_1_raw_tilt_adjusted.csv" in aws-l0/raw/KAN_U/archive. I am registering KAN_U_2013_1_raw.txt and KAN_U_2013_2_raw.txt in the toml file instead.
 - In the Edition 3, the file "KAN_U_2010-2012_raw_transmitted_tilt_adjusted.csv" was used but it is not a logger file. how should it be registered in the KAN_U.toml file?

**Comment by robertfausto** [comment]
I uploaded "KAN_U_2013_1_raw_tilt_adjusted.csv" to the archive. "KAN_U_2010-2012_raw_transmitted_tilt_adjusted.csv" should be a data file.

**Comment by BaptisteVandecrux** [comment]
Now released on the dataverse: https://doi.org/10.22008/FK2/IW73UU
