### ISSUE TITLE
NSE 2022 Lufft constant/strange values in l3 and tx

### ISSUE THREAD

**Issue by jasonebox** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#24]
from at least 1 July...

for l3 the Lufft t_i was nan, p_i and rh_i were constant until sometime in Oct 2022, then came back to life? 
![NSE](https://user-images.githubusercontent.com/32133350/212324566-e49e1f46-c0b3-41fb-b62f-20797d4ad272.png)

for tx, Lufft  t_u is not reporting values above c. -20
![image](https://user-images.githubusercontent.com/32133350/212325487-a13337fc-49ac-4e47-a662-778b732d76e4.png)

see my next issue about filtering

**Comment by patrickjwright** [comment]
I believe this is the other way around. The second plot is instantaneous vars, and the first plot is hourly (`_u`) vars.

**Comment by BaptisteVandecrux** [comment]
First spurious period removed from p_u and rh_u:
![image](https://user-images.githubusercontent.com/35140661/217203198-477b5726-4adb-40ad-be59-1b729cb3b4d4.png)
![image](https://user-images.githubusercontent.com/35140661/213466651-bd99a2e9-2dac-4393-8efa-dc785d32fc19.png)

using https://github.com/GEUS-Glaciology-and-Climate/pypromice/tree/fixing-data
and the flag file added here:
https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/tree/master/flags

needs to be reviewed before it goes into production

**Comment by BaptisteVandecrux** [comment]
Now released on the dataverse: https://doi.org/10.22008/FK2/IW73UU
