### ISSUE TITLE
Pressure transducer depth

### ISSUE THREAD

**Issue by mankoff** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#4]
@BaptisteVandecrux

**Comment by BaptisteVandecrux** [comment]
This is already part of the product.
I have started to implement adjustments that are trying to keep the continuity of the pressure transducer.
See, e.g. KPC_L here https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/issues/132
I now realize that those adjustments are actually reconstruction the ice surface height, and not the pressure transducer depth (which for instance cannot be negative). In [my feature request](https://github.com/GEUS-Glaciology-and-Climate/pypromice/issues/10) on pypromice I am mentioning "ice_surface_height" as a new variable.
I'm closing this ticket as it is not a data issue, but we can keep talking about the new variables on [#10](https://github.com/GEUS-Glaciology-and-Climate/pypromice/issues/10).
