### ISSUE TITLE
NEM wind dir and speed lower constant from Nov 2022

### ISSUE THREAD

**Issue by BaptisteVandecrux** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#51]
![billede](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/6d6c9157-a4ae-49fd-b8d0-18d3e5cc69a1)

**Comment by RasmusBahbah** [comment]
Picture of Lower Wind Sensor
![IMG_20230701_120319](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/114926145/8f4b7f0a-19f7-4da3-8913-828e9c54451e)
