### ISSUE TITLE
NUK_L is on a serac in a crevasse field

### ISSUE THREAD

**Issue by mankoff** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#57]
## What is the issues?

In August 2023 NUK_L station visit showed it is on a serac in a crevasse field. This probably does not influence ALL_SENSORs (as tagged), but I figure it is better to be overly restrictive, and leave it to GEUS PROMICE to decide which data is still valid.

I assume air temperature is still valid. But ice temperature may not be, as the thermistor string may have been exposed to lateral heating from the side of the crevasses. Wind speed is reliant on roughness scale, etc.

![foo](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/145117/801e2388-e01e-45a8-af07-2f2632d18237)

![PXL_20230818_111351822](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/145117/0d931332-a2a9-4b0a-aa84-fa3a86282670)

**Comment by BaptisteVandecrux** [comment]
I don't see this as a data-related issue. 
But that prompts the need for a catalogue of station pictures that users could easily navigate through.
For the historical GC-Net stations, we posted it on Zenodo (which doesn't allow to browse through pictures):
 https://zenodo.org/doi/10.5281/zenodo.7839788

Yet that seems quite low priority compared to other development projects.
