### ISSUE TITLE
JAR gps_lat gps_lon wrong value for few weeks in June.July 2022

### ISSUE THREAD

**Issue by BaptisteVandecrux** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#74]
![image](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/e2ff05e8-2445-454e-a76b-cef33fe04137)

**Comment by BaptisteVandecrux** [comment]
now filtered:
![billede](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/assets/35140661/affddc8e-8e8b-4762-a89f-3291912dc19d)

**Comment by BaptisteVandecrux** [comment]
fixed in dataverse V18

**Comment by jasonebox** [comment]
do we understand why the lat lon shifted but elev didn't?

There was a case when the TOML files associated the wrong sites, if I recall it was CP1 and another site. But here, the elevation seems ok

By the way, technically the data meteorological users (including ECMWF) is "elevation" that's the height above mean sea level. Altitude is above an ellipsoid, not what typical users want. So, technically, the name should change. 
Elevation: https://en.wikipedia.org/wiki/Elevation
Altitude: https://en.wikipedia.org/wiki/Geodetic_coordinates#:~:text=Similarly%2C%20geodetic%20altitude%20is%20defined,radial%20line%20to%20the%20geocenter.

**Comment by BaptisteVandecrux** [comment]
I don't think there's a station swap here.
The constant values for lat and lon indicate that the GPS stopped working and logger program duplicated the last valid data point which in that case was a wrong measurement when the station was powered again.

Thanks for the precision on elevation/altitude. This should be updated in pypromice ( and I moved your related issue there: https://github.com/GEUS-Glaciology-and-Climate/pypromice/issues/239) since it is about the variable description/labelling.
