### ISSUE TITLE
KPC_L max albedo reduced from 0.8 to 0.6 after 2020

### ISSUE THREAD

**Issue by BaptisteVandecrux** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#83]
0.6 is too low for new snow.
See the reduction in usr_cor after 2020

![image](https://github.com/GEUS-Glaciology-and-Climate/pypromice/assets/35140661/22db2b25-10ef-4152-a8ca-72eda83cb500)

**Comment by mvantiggelen** [comment]
Since there is a also a [shift in longwave radiation from July 2019](https://github.com/GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues/issues/130), it could be due to a change in CNR4 calibration coefficients.

**Comment by BaptisteVandecrux** [comment]
Caused by swapped calibration constants at KPC_L and KPC_U. Now fixed on thredds and in dataverse release V20 https://doi.org/10.22008/FK2/IW73UU
