### ISSUE TITLE
Uneasy issue reporting

### ISSUE THREAD

**Issue by BaptisteVandecrux** [GEUS-Glaciology-and-Climate/PROMICE-AWS-data-issues#9]
I have been trying to use GitHub labelling system to report issues in the GC-Net station data:

Examples:
https://github.com/BaptisteVandecrux/GC-Net-evaluation/issues
https://github.com/BaptisteVandecrux/GC-Net-evaluation/issues/7

I find this system uneasy:
- lots of clicking: what if I have to label all years between 2000 and 2020 ?
- no straightforward way to transform the reported issues into a file summarizing issues at a given site
- no straightforward way to submit f.e. a text file with a list of suspicious period for a given sensor (see attached file)
[ErrorData.xlsx](https://github.com/GEUS-PROMICE/PROMICE-AWS-data-issues/files/5297042/ErrorData.xlsx)
![image](https://user-images.githubusercontent.com/35140661/94524383-d29c2180-0232-11eb-82b0-a8fbd109dfa6.png)

**Comment by mankoff** [comment]
One possible workflow: For those of us generating large numbers of issues, we track them in a spreadsheet as you show above (local or Google Docs). Then, the issues can be generated via the GitHub API. See for example https://gist.github.com/JeffPaine/3145490

**Comment by mankoff** [comment]
Note that there is no API to upload images. The issue-creator script could upload to a 3rd party site (Imgur?) and then embed.

**Comment by mankoff** [comment]
Solution after offline discussion: For now, QA/QC is internal and can be done with a local spreadsheet that better supports cloning rows, adding specific start- and stop- times, etc. Issues that are solved in pre-public data do not need to be published here. Ideally all issues solved and this DB is empty, but we can populate this public DB, and/or accept public input via this DB, later.

**Comment by mankoff** [comment]
This site is now referenced in a soon-to-be-published paper https://doi.org/10.5194/essd-2021-80. For mass issue submission, GitHub API should be used. For individual issues.
